name: Mi workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar
        run: pip install pytest
    
      - name: Probar codigo
        run: python3 test.py
