name: Mi workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        run: actions/checkout@v4
      - name: Instalar
        run: pip install pytest
    
      - name: Probar codigo
        run: pytest test.py
